"use strict";
const $ = s => document.querySelector(s);
const esc = s => String(s ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const state = {boot:null, run:null, audit:null, sql:null, model:null, evals:null, runs:[], view:"overview", selectedSkill:null};
const titles = {overview:"Mission control",audit:"SQL & lineage",investigate:"Investigation lab",model:"Kimball studio",skills:"Skill library",runs:"Run ledger"};
let toastTimer;
function toast(message){$("#toast").textContent=message;$("#toast").classList.add("visible");clearTimeout(toastTimer);toastTimer=setTimeout(()=>$("#toast").classList.remove("visible"),5000);}
async function api(path, body){
  const token=sessionStorage.getItem("flightcheck-token");
  const response=await fetch(path,{method:body===undefined?"GET":"POST",headers:{...(body!==undefined?{"Content-Type":"application/json"}:{}),...(token?{Authorization:`Bearer ${token}`}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});
  if(response.status===401){if(!$("#token-dialog").open)$("#token-dialog").showModal();throw new Error("Enter the workspace access token.");}
  if(!response.ok){const error=await response.json().catch(()=>({detail:"Request failed"}));throw new Error(typeof error.detail==="string"?error.detail:JSON.stringify(error.detail));}
  return response.headers.get("content-type")?.includes("application/json")?response.json():response.text();
}
const pill = status => `<span class="status ${esc(status)}">${esc(String(status).replaceAll("_"," "))}</span>`;
const hero = (eyebrow,title,subtitle,actions="") => `<section class="hero"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${subtitle}</p></div><div class="actions">${actions}</div></section>`;
const panel = (title,subtitle,body,action="")=>`<section class="panel"><div class="panel-head"><div><h2>${title}</h2>${subtitle?`<p>${subtitle}</p>`:""}</div>${action}</div>${body}</section>`;
function gateStrip(run){const gates=run?.gates||state.boot.gates.map((g,i)=>({id:g[0],index:i,title:g[1],status:"not_run",detail:g[2]}));return `<div class="gate-row">${gates.map(g=>`<div class="gate ${esc(g.status)}" title="${esc(g.detail)}"><div class="gate-top"><span>GATE 0${g.index}</span><span class="gate-symbol">${g.status==="pass"?"✓":g.status==="fail"?"!":g.status==="not_applicable"?"—":"○"}</span></div><h3>${esc(g.title)}</h3><p>${esc(g.detail)}</p></div>`).join("")}</div>`;}
function findings(items,limit=Infinity){if(!items?.length)return `<div class="empty">No static findings in this scope. Live data checks remain separate.</div>`;return items.slice(0,limit).map(f=>`<div class="finding"><div class="finding-top"><h3>${esc(f.rule.replaceAll("_"," "))}</h3>${pill(f.waived?"waived":f.severity==="block"?"blocked":"review")}</div><p>${esc(f.message)}</p><div class="code">${esc(f.subject)}</div><p>${esc(f.remediation)}</p></div>`).join("");}
function graph(audit){
  if(!audit)return '<div class="empty">Load a manifest to explore dependencies.</div>';
  const groups=[['source'],['staging'],['intermediate'],['mart','serving'],['consumer']];
  const labels=['SOURCE','STAGING','INTERNAL','PUBLISHED','CONSUMERS'];const pos={};
  groups.forEach((layers,col)=>audit.nodes.filter(n=>layers.includes(n.layer)).forEach((n,row)=>pos[n.id]={x:col*160+12,y:row*75+58}));
  const maxRows=Math.max(...groups.map(g=>audit.nodes.filter(n=>g.includes(n.layer)).length),1);const height=maxRows*75+82;
  const edges=audit.edges.filter(e=>pos[e.source]&&pos[e.target]).map(e=>{const a=pos[e.source],b=pos[e.target];return `<path d="M${a.x+137} ${a.y+22} C${a.x+162} ${a.y+22},${b.x-25} ${b.y+22},${b.x} ${b.y+22}" fill="none" stroke="${e.allowed?'#506f75':'#e88795'}" stroke-width="${e.allowed?1.2:1.8}" ${e.allowed?'':'stroke-dasharray="4 4"'} opacity=".8"/>`;}).join('');
  const nodes=audit.nodes.filter(n=>pos[n.id]).map(n=>{const p=pos[n.id],warn=audit.edges.some(e=>e.target===n.id&&!e.allowed);const chunks=n.name.length>21?[n.name.slice(0,21),n.name.slice(21,40)]:[n.name];return `<g class="graph-node" tabindex="0" role="button" aria-label="Inspect ${esc(n.name)}" data-node="${esc(n.id)}"><rect x="${p.x}" y="${p.y}" width="137" height="45" rx="6" fill="${warn?'#2c202d':n.layer==='mart'||n.layer==='serving'?'#221e36':'#172130'}" stroke="${warn?'#995b6a':'#394358'}"/><circle cx="${p.x+10}" cy="${p.y+13}" r="2.5" fill="${warn?'#ff929a':n.layer==='consumer'?'#65dbc6':'#b9a0ff'}"/>${chunks.map((v,i)=>`<text x="${p.x+18}" y="${p.y+16+i*13}" font-size="8.5" fill="#dbe2ef">${esc(v)}</text>`).join('')}</g>`;}).join('');
  return `<div class="lineage"><svg viewBox="0 0 815 ${height}" role="img" aria-label="Dependency graph. Dashed coral lines identify layer bypasses.">${labels.map((l,i)=>`<text x="${i*160+14}" y="24" fill="#7e8aa3" font-size="8" letter-spacing="1.5">${l}</text>`).join('')}${edges}${nodes}</svg></div><div class="graph-detail" id="graph-detail">Select a node to inspect its declared grain, owner, and downstream impact.</div>`;
}
function overview(){
  const r=state.run,a=state.audit;const mismatch=r?.diff? r.diff.missing_keys.count+r.diff.changed_records.count+r.diff.duplicate_keys.right.count:0;
  return hero('Engineering assurance','Trust the result.<br><span class="accent">Prove the path.</span>','A repeatable system for legacy SQL, dimensional models, and the evidence behind every data product.',`<button class="button subtle" data-action="eval">Run evaluation suite</button><button class="button primary" data-action="demo">Run investigation ↗</button>`)+
  `<div class="stats"><div class="stat"><span class="stat-icon">⌁</span><div class="label">CONSUMPTION VIOLATIONS</div><div class="number red">${a?.findings.filter(f=>f.rule==='LAYER_BYPASS').length??'—'}</div><div class="caption">Direct paths into internal models</div></div><div class="stat"><span class="stat-icon">◎</span><div class="label">RECORD DEFECTS</div><div class="number purple">${mismatch||'0'}</div><div class="caption">Missing keys, value changes, duplicate grain</div></div><div class="stat"><span class="stat-icon">▤</span><div class="label">ENGINEERING SKILLS</div><div class="number">${state.boot.catalog.skills.length}</div><div class="caption">Routed by task and failure mode</div></div><div class="stat"><span class="stat-icon">✓</span><div class="label">REGRESSION CHECKS</div><div class="number green">${state.evals?`${state.evals.passed}/${state.evals.total}`:'—'}</div><div class="caption">${state.evals?'Executed synthetic evaluations':'Run the suite to measure'}</div></div></div>`+
  `<div class="section-line"><h2>The evidence sequence</h2>${r?pill(r.status):pill('not_run')}</div>${gateStrip(r)}`+
  `<div class="grid-two"><div>${panel('Dependency flight path','Imported dbt artifact · select any asset',graph(a),`<div class="legend"><span><i class="dot"></i>Allowed path</span><span><i class="dot red"></i>Layer bypass</span></div>`)}<div class="callout"><strong>Equal counts can hide different records.</strong> The default investigation compares six rows to six rows. A join duplicates one operation, a filter drops another, and a cost expression changes a third.</div></div><div>${panel('Findings that need attention','Architecture findings are independent of data parity.',findings(a?.findings,3),'<a class="button small subtle" href="#audit">Inspect</a>')}${panel('The operating model','Small, ordered checks. Stop unsupported inference.',`<div class="panel-body"><p class="small muted">Discover → establish evidence → declare grain → build → reconcile → review.</p><div class="actions"><a class="button small" href="#skills">Explore skills</a><a class="button small subtle" href="#model">Design a model</a></div></div>`)}</div></div>`;
}
function auditView(){return hero('Architecture & dependencies','Find the bypass.','Inspect compiled BigQuery SQL and dbt artifacts. Unknown relations and unresolved lineage stay visible.')+
  `<div class="grid-two"><div>${panel('SQL workbench','SQL is parsed locally; this screen does not execute warehouse queries.',`<div class="panel-body"><label>Consumer / model layer<select id="sql-layer">${['consumer','serving','mart','intermediate','staging'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Compiled SQL<textarea id="sql-editor" spellcheck="false">WITH operations AS (
    SELECT * FROM &#96;synthetic.intermediate.operation_events&#96;
)
SELECT DISTINCT event_id, work_order_id, cost_usd
FROM operations</textarea></label><div class="actions"><button class="button primary" data-action="audit-sql">Audit SQL</button><button class="button" data-action="load-clean-sql">Load published example</button></div></div>`)}<div id="sql-results">${state.sql?panel('SQL findings',`${state.sql.relations.length} physical relations resolved`,findings(state.sql.findings),pill(state.sql.status)):''}</div></div><div>${panel('dbt manifest','Upload manifest.json from your development compile.',`<div class="panel-body"><label>Manifest file<input id="manifest-file" type="file" accept=".json,application/json"></label><button class="button" data-action="example-manifest">Load synthetic manifest</button><p class="meta-note">Metadata is inspected on this server and saved in the local run ledger. Out-of-manifest BI queries require separate inventory.</p></div>`)}<div class="callout"><strong>Internal models are implementation details.</strong><br>Published marts and serving models form the consumer interface. Exceptions are scoped to a finding fingerprint, independently reviewed, and time limited.</div></div></div>`+
  panel('Lineage & blast radius',state.audit?.scope||'',graph(state.audit),state.audit?pill(state.audit.status):'')+panel('Manifest findings','Static contracts are prerequisites; they do not certify data.',findings(state.audit?.findings));}
function diffView(diff){if(!diff)return '<div class="empty">The record comparison has not run because a prerequisite gate failed.</div>';return `<div class="panel-body"><div class="difference-grid">${[[`${diff.left_count} / ${diff.right_count}`,'Left / right row count'],[diff.missing_keys.count,'Keys missing on right'],[diff.changed_records.count,'Records with changed values'],[diff.duplicate_keys.right.count,'Duplicate keys on right']].map(([n,l])=>`<div><strong>${esc(n)}</strong><span>${l}</span></div>`).join('')}</div></div><div class="table-wrap"><table><thead><tr><th>Witness</th><th>Difference</th><th>Evidence</th></tr></thead><tbody>${diff.missing_keys.sample.map(k=>`<tr><td class="code">${esc(k.join(' / '))}</td><td>Missing key</td><td>Present in baseline; absent in candidate.</td></tr>`).join('')}${diff.changed_records.sample.map(r=>`<tr><td class="code">${esc(r.key.join(' / '))}</td><td>Value changed</td><td>${r.changes.map(c=>`${esc(c.column)}: ${c.left_present?esc(JSON.stringify(c.left)):'MISSING'} → ${c.right_present?esc(JSON.stringify(c.right)):'MISSING'}`).join('<br>')}</td></tr>`).join('')}${diff.duplicate_keys.right.sample.map(r=>`<tr><td class="code">${esc(r.key.join(' / '))}</td><td>Duplicate grain</td><td>${r.multiplicity} rows for one declared key.</td></tr>`).join('')}${diff.status==='equal'?'<tr><td colspan="3">All compared records agree at the supplied grain and tolerances.</td></tr>':''}</tbody></table></div>`;}
function investigate(){const r=state.run;return hero('Evidence lab','Investigate with a witness.','Run a failure scenario or import a typed evidence bundle. A failed prerequisite stops the comparison.',r?`<button class="button" data-action="export-run">Export evidence</button><button class="button primary" data-action="handoff">Copy Claude handoff</button>`:'')+
  `<div class="investigation-bar"><label>Executed synthetic scenario<select id="case-select">${Object.entries(state.boot.cases).map(([k,v])=>`<option value="${k}">${esc(v)}</option>`).join('')}</select></label><button class="button primary" data-action="run-case">Run all gates</button><label>Import evidence JSON<input type="file" id="evidence-file" accept=".json"></label></div>`+
  `${r?`<div class="review-summary">${pill(r.status)}<span>${esc(r.title)}</span></div>`:''}${gateStrip(r)}`+
  panel('Record-level reconciliation',r?.provenance==='synthetic-executed'?'Actually executed in SQLite · synthetic records':r?.provenance||'No run selected',diffView(r?.diff))+
  (r?.trace?panel('Where the records change',r.trace.scope,`<div class="table-wrap"><table><thead><tr><th>Transition</th><th>Rows</th><th>Lost keys</th><th>Duplicate keys</th><th>Result</th></tr></thead><tbody>${r.trace.transitions.map(t=>`<tr><td>${esc(t.from)} → ${esc(t.to)}</td><td>${t.before} → ${t.after}</td><td>${t.missing}</td><td>${t.duplicate_keys}</td><td>${pill(t.status)}</td></tr>`).join('')}</tbody></table></div>`):'')+
  `<div class="callout"><strong>This is an evidence review, not a certification button.</strong> A clean comparison still needs business-owner review, model contracts, consumer migration, and release controls. Imported observations are explicitly marked unattested.</div>`+
  panel('Bring your own record sets','JSON arrays, up to 50,000 rows per side. Missing fields differ from NULL.',`<div class="panel-body"><div class="field-grid"><label>Baseline JSON<textarea id="left-json" spellcheck="false">[{"id":"A","value":10}]</textarea></label><label>Candidate JSON<textarea id="right-json" spellcheck="false">[{"id":"A","value":11}]</textarea></label></div><label>Grain columns, comma separated<input id="diff-keys" value="id"></label><button class="button" data-action="custom-diff">Compare records</button><div id="custom-diff-result"></div></div>`);}
function modelView(){const spec=state.boot.model_example,m=state.model;return hero('Dimensional design','Declare the grain first.','Turn an explicit model contract into dbt SQL, schema tests, and reviewable design artifacts.')+
  `<div class="grid-two"><div>${panel('Model contract','Edit the business process, grain, keys, history policy, and measures.',`<div class="panel-body"><label>Typed model specification<textarea id="model-editor" spellcheck="false">${esc(JSON.stringify(state.modelInput||spec,null,2))}</textarea></label><div class="actions"><button class="button primary" data-action="scaffold">Validate & generate</button><button class="button" data-action="reset-model">Reset example</button></div></div>`)}</div><div>${panel('Example dimensional shape','A fact at one declared grain, with conformed dimensions.',`<div class="panel-body"><div class="model-star"><div><h3>dim_work_order</h3><ul><li>work_order_key</li><li>business work-order ID</li><li>product / revision context</li></ul></div><div><h3>Time context</h3><ul><li>occurred_at · UTC</li><li>source event time</li><li>ingestion watermark</li></ul></div><div class="fact"><span class="eyebrow">TRANSACTION FACT</span><h3>fct_operation_event</h3><ul><li>event_id · grain key</li><li>work_order_key · dimension</li><li>duration_seconds · additive</li><li>cost_usd · additive, defined currency</li></ul></div></div><p class="meta-note">Illustrative design only. The editable contract is authoritative for generated files.</p></div>`)}<div class="callout"><strong>Grain is a business statement.</strong><br>A unique ID is a testable key, but it does not explain what one row represents. Model approval needs both.</div></div></div><div id="model-results">${m?modelResults(m):''}</div>`;}
function modelResults(m){return panel('Design assessment','Generated SQL is a scaffold; run and reconcile it in your development project.',findings(m.assessment.findings),pill(m.assessment.status))+(Object.keys(m.files).length?panel('Generated dbt artifacts','Explicit columns, schema contracts, key tests, and relationships.',Object.entries(m.files).map(([name,text])=>`<details><summary>${esc(name)}</summary><pre>${esc(text)}</pre></details>`).join(''),'<button class="button small" data-action="download-model">Download ZIP</button>'):'');}
function skillsView(){return hero('Reusable engineering intelligence','A playbook for the failure mode.','Skills route Claude to the right protocol. Executable checks make the claims testable.',`<input id="skill-search" class="skill-search" placeholder="Search grain, freshness, legacy…" aria-label="Search skills">`)+`<div class="tab-buttons"><button class="button selected" data-action="skill-filter" data-filter="all">All skills</button><button class="button" data-action="skill-filter" data-filter="Evidence">Evidence</button><button class="button" data-action="skill-filter" data-filter="Modeling">Modeling</button><button class="button" data-action="skill-filter" data-filter="Delivery">Delivery</button></div><div class="skill-grid" id="skill-grid">${skillCards(state.boot.catalog.skills)}</div>`+`<div class="section-line"><h2>Protocols</h2><span class="muted small">Versioned workflows in the repository</span></div><div style="height:15px"></div><div class="skill-grid">${state.boot.catalog.protocols.map(p=>`<button class="skill-card" data-protocol="${esc(p.id)}"><span class="skill-icon">↗</span><h3>${esc(p.title)}</h3><small>OPEN PROTOCOL</small></button>`).join('')}</div>`;}
function skillCards(skills){return skills.map(s=>`<button class="skill-card" data-skill="${esc(s.id)}"><span class="skill-icon">${s.category==='Evidence'?'◎':s.category==='Modeling'?'◇':'⌁'}</span><h3>${esc(s.title)}</h3><p>${esc(s.summary)}</p><small>${esc(s.category.toUpperCase())} · /${esc(s.id)}</small></button>`).join('')||'<p class="empty">No matching skills.</p>';}
function runsView(){return hero('Reproducibility & review','Every run leaves a record.','The ledger contains actual runs from this workspace. Input hashes bind results to evidence and policy.',`<button class="button" data-action="eval">Run evaluations</button><button class="button subtle" data-action="refresh-runs">Refresh</button>`)+
  (state.evals?panel('Regression evaluation',state.evals.scope,`<div class="table-wrap"><table><thead><tr><th>Scenario</th><th>Expected</th><th>Observed</th><th>Result</th></tr></thead><tbody>${state.evals.checks.map(c=>`<tr><td>${esc(c.name)}</td><td class="code">${esc(c.expected)}</td><td class="code">${esc(c.actual)}</td><td>${pill(c.passed?'pass':'fail')}</td></tr>`).join('')}</tbody></table></div>`,pill(state.evals.status)):'')+
  panel('Run history',`${state.runs.length} most recent runs · append-only through the app`,state.runs.length?`<div class="table-wrap"><table><thead><tr><th>Run</th><th>Type</th><th>Created</th><th>Result</th><th>Evidence</th></tr></thead><tbody>${state.runs.map(r=>`<tr><td>${esc(r.title)}<br><span class="code">${esc(r.id.slice(0,8))}</span></td><td>${esc(r.kind)}</td><td>${esc(new Date(r.created_at).toLocaleString())}</td><td>${pill(r.status)}</td><td><button class="button small subtle" data-open-run="${esc(r.id)}">Open</button> <button class="button small subtle" data-export-id="${esc(r.id)}">JSON</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Run an investigation or audit to begin.</div>')+`<div class="callout">Local SQLite and content hashes provide reproducibility and corruption checks. They are not immutable audit storage or authenticated human approval.</div>`;}
function render(){if(!state.boot)return;const view=location.hash.slice(1)||'overview';state.view=titles[view]?view:'overview';$('#view-label').textContent=titles[state.view];document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.dataset.view===state.view));$('#content').innerHTML=({overview,audit:auditView,investigate,model:modelView,skills:skillsView,runs:runsView}[state.view])();$('#content').className='view-fade';}
async function updateRuns(){state.runs=await api('/api/runs');}
function download(name,content,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('Copied to clipboard.');}catch{download('claude-handoff.md',text,'text/markdown');toast('Clipboard unavailable; downloaded the handoff.');}}
async function action(name,button){
 switch(name){
  case'demo': state.run=await api('/api/demo/masked-loss',{});location.hash='investigate';break;
  case'run-case': {const selected=$('#case-select').value;state.run=await api(`/api/demo/${selected}`,{});render();$('#case-select').value=selected;await updateRuns();return;}
  case'eval':state.evals=await api('/api/evaluations',{});toast(`${state.evals.passed}/${state.evals.total} regression scenarios passed.`);break;
  case'audit-sql': {state.sql=await api('/api/audit/sql',{sql:$('#sql-editor').value,layer:$('#sql-layer').value,title:'SQL workbench audit'});$('#sql-results').innerHTML=panel('SQL findings',`${state.sql.relations.length} physical relations resolved`,findings(state.sql.findings),pill(state.sql.status));await updateRuns();return;}
  case'load-clean-sql':$('#sql-editor').value='SELECT event_id, work_order_key, occurred_at, cost_usd\nFROM `synthetic.serving.rpt_operations`';return;
  case'example-manifest':state.audit=await api('/api/audit/manifest',state.boot.manifest_example);break;
  case'scaffold':state.modelInput=JSON.parse($('#model-editor').value);state.model=await api('/api/models',state.modelInput);$('#model-results').innerHTML=modelResults(state.model);$('#model-results').scrollIntoView({behavior:'smooth',block:'start'});await updateRuns();return;
  case'reset-model':state.modelInput=null;state.model=null;break;
  case'download-model':{const token=sessionStorage.getItem('flightcheck-token');const response=await fetch(`/api/runs/${state.model.id}/scaffold.zip`,{headers:token?{Authorization:`Bearer ${token}`}:{}});if(!response.ok)throw new Error('Could not download model');download('dbt-model-scaffold.zip',await response.blob(),'application/zip');return;}
  case'export-run':download(`evidence-${state.run.id.slice(0,8)}.json`,JSON.stringify(state.run,null,2));return;
  case'handoff':await copy(await api(`/api/runs/${state.run.id}/handoff`));return;
  case'custom-diff':{const r=await api('/api/reconcile',{left:JSON.parse($('#left-json').value),right:JSON.parse($('#right-json').value),keys:$('#diff-keys').value.split(',').map(x=>x.trim()).filter(Boolean)});$('#custom-diff-result').innerHTML=diffView(r);await updateRuns();return;}
  case'refresh-runs':break;
  case'skill-filter':document.querySelectorAll('[data-action="skill-filter"]').forEach(b=>b.classList.toggle('selected',b===button));state.skillFilter=button.dataset.filter;filterSkills();return;
 }
 await updateRuns();render();
}
function filterSkills(){const q=($('#skill-search')?.value||'').toLowerCase();$('#skill-grid').innerHTML=skillCards(state.boot.catalog.skills.filter(s=>(!state.skillFilter||state.skillFilter==='all'||s.category===state.skillFilter)&&`${s.title} ${s.summary} ${s.id}`.toLowerCase().includes(q)));}
document.addEventListener('click',async event=>{
 const button=event.target.closest('[data-action]');
 try{
  if(button){button.disabled=true;await action(button.dataset.action,button);return;}
  const skill=event.target.closest('[data-skill]'),protocol=event.target.closest('[data-protocol]');
  if(skill||protocol){const item=skill?state.boot.catalog.skills.find(x=>x.id===skill.dataset.skill):state.boot.catalog.protocols.find(x=>x.id===protocol.dataset.protocol);state.selectedSkill=item;$('#dialog-title').textContent=item.title;$('#dialog-body').textContent=item.content;$('#copy-skill').textContent=skill?'Copy invocation':'Copy protocol';$('#detail-dialog').showModal();return;}
  const node=event.target.closest('[data-node]');if(node){const n=state.audit.nodes.find(n=>n.id===node.dataset.node);const impact=await api(`/api/runs/${state.audit.id}/impact/${encodeURIComponent(n.id)}`);$('#graph-detail').innerHTML=`<strong>${esc(n.name)}</strong> · ${esc(n.layer)} · ${impact.descendants.length} downstream assets<br>Grain: ${esc(n.grain||'Undeclared')} · Owner: ${esc(n.owner||'Undeclared')}`;return;}
  const exp=event.target.closest('[data-export-id]');if(exp){const r=await api(`/api/runs/${exp.dataset.exportId}`);download(`flightcheck-${r.id.slice(0,8)}.json`,JSON.stringify(r,null,2));return;}
  const open=event.target.closest('[data-open-run]');if(open){const r=await api(`/api/runs/${open.dataset.openRun}`);if(r.gates){state.run=r;location.hash='investigate';}else if(r.kind==='manifest'){state.audit=r;location.hash='audit';}else if(r.kind==='sql'){state.sql=r;location.hash='audit';}else if(r.kind==='evaluations'){state.evals=r;render();}else if(r.assessment){state.model=r;location.hash='model';}else{state.selectedSkill={title:'Record comparison',content:JSON.stringify(r,null,2)};$('#dialog-title').textContent='Record comparison';$('#dialog-body').textContent=state.selectedSkill.content;$('#copy-skill').textContent='Copy JSON';$('#detail-dialog').showModal();}}
 }catch(error){toast(error.message);}finally{if(button)button.disabled=false;}
});
document.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.matches('[data-node]')){event.preventDefault();event.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
document.addEventListener('input',event=>{if(event.target.id==='skill-search')filterSkills();});
document.addEventListener('change',async event=>{if(!['manifest-file','evidence-file'].includes(event.target.id))return;try{const file=event.target.files[0];if(!file)return;if(file.size>10*1024*1024)throw new Error('File exceeds 10 MiB');const data=JSON.parse(await file.text());if(event.target.id==='manifest-file'){state.audit=await api('/api/audit/manifest',data);}else{state.run=await api('/api/evidence',data);}await updateRuns();render();}catch(e){toast(e.message);}});
$('#close-dialog').onclick=()=>$('#detail-dialog').close();$('#copy-skill').onclick=()=>copy(state.selectedSkill.id&&state.boot.catalog.skills.some(s=>s.id===state.selectedSkill.id)?`Use /${state.selectedSkill.id} from .claude/skills/${state.selectedSkill.id}/SKILL.md. Follow CLAUDE.md and config/policy.yml. Produce evidence-backed findings and a reviewable patch.`:state.selectedSkill.content);
$('#token-button').onclick=()=>$('#token-dialog').showModal();$('#cancel-token').onclick=()=>$('#token-dialog').close();$('#token-form').onsubmit=async e=>{e.preventDefault();sessionStorage.setItem('flightcheck-token',$('#access-token').value);$('#access-token').value='';$('#token-dialog').close();await init();};
window.addEventListener('hashchange',render);
async function init(){try{state.boot=await api('/api/bootstrap');await updateRuns();const previous=state.runs.find(r=>r.kind==='investigation'),previousAudit=state.runs.find(r=>r.kind==='manifest'),previousEval=state.runs.find(r=>r.kind==='evaluations');state.run=previous?await api(`/api/runs/${previous.id}`):await api('/api/demo/masked-loss',{});state.audit=previousAudit?await api(`/api/runs/${previousAudit.id}`):await api('/api/audit/manifest',state.boot.manifest_example);if(previousEval)state.evals=await api(`/api/runs/${previousEval.id}`);await updateRuns();render();}catch(e){$('#content').innerHTML=`<div class="empty">${esc(e.message)}</div>`;toast(e.message);}}
init();
